# Generated by Django 4.0.3 on 2022-03-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Scaler@123', max_length=55),
            preserve_default=False,
        ),
    ]
