# Generated by Django 4.0.3 on 2022-03-23 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_networkedge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networkedge',
            unique_together={('from_user', 'to_user')},
        ),
    ]
