# Generated by Django 4.0.3 on 2022-03-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_networkedge_unique_together'),
        ('content', '0003_alter_postmedia_media_file_postlikes_postcomments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlikes',
            unique_together={('post', 'liked_by')},
        ),
    ]
