# Generated by Django 3.2.12 on 2022-03-31 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_postlikes_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'permissions': (('can_publish_posts', 'Can Publish posts'),)},
        ),
    ]
