# Generated by Django 3.2.12 on 2022-05-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_userpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='location',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
