# Generated by Django 3.2.12 on 2022-05-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_userpost_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTagMasterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userpost',
            name='tags',
            field=models.ManyToManyField(to='content.PostTagMasterList'),
        ),
    ]
